name: Build and Deploy to Staging

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Registry
        run: docker login registry.fanzru.dev -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and tag Docker image
        run: docker build -t registry.fanzru.dev/kangtech-web:staging .

      - name: Push image to registry
        run: docker push registry.fanzru.dev/kangtech-web:staging

      - name: Deploy to staging via Portainer webhook
        env:
          PORTAINER_STAGING_WEBHOOK_URL: ${{ secrets.PORTAINER_STAGING_WEBHOOK_URL }}
        run: |
          curl -X POST "$PORTAINER_STAGING_WEBHOOK_URL"
