name: Build and Deploy to Staging

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Registry
        run: docker login registry.fanzru.dev -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and tag Docker image
        run: docker build --build-arg NODE_ENV=staging --build-arg PORT=3011 -t registry.fanzru.dev/kangtech-web:staging .

      - name: Push image to registry
        run: docker push registry.fanzru.dev/kangtech-web:staging

      - name: Deploy to staging via Portainer webhook
        run: |
          echo "Triggering Portainer webhook..."
          curl -X POST \
            -H "Content-Type: application/json" \
            -w "HTTP Status: %{http_code}\n" \
            --fail-with-body \
            "${{ secrets.PORTAINER_STAGING_WEBHOOK_URL }}"
